export interface AssetsReadModel {
    id: number;
    name: string;
    spaceId: number;
    value: number;
    spaceName: string;
    purchaseDate: string;
    description: string;
    category: string;
    createdAt?: string;
    status?: 'active' | 'inactive' | 'maintenance' | 'sold';
    warrantyEnd?: string;
    additionalInfo?: string;
    warrantyEndDate?: string;
    warrantyStatus?: 1 | 2 | 3 | null | undefined;
    warrantyProvider?: string | null;
    warrantyStartDate?: string | null;
    insuranceEndDate?: string;
    insuranceStatus?: 0 | 1 | 2 | null | undefined;
    insuranceValue?: number | null;
    insuranceCompany?: string | null;
    insuranceStartDate?: string | null;
    customTrackerName?: string | null;
    customTrackerEndDate?: string | null;
    customTrackerStatus?: 0 | 1 | 2 | 3 | null | undefined;
    warrantyDocumentId?: string | null;
    warrantyDocumentFileName?: string | null;
    insuranceDocumentId?: string | null;
    insuranceDocumentFileName?: string | null;
    isLoaned?: boolean;
    loanedToName?: string | null;
    loanCondition?: string | null;
    loanNotes?: string | null;
    loanedAt?: string | null;
    loanReturnedAt?: string | null;
    loanConditionOnReturn?: string | null;
    barcode?: string | null;
}